// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need DDL rights, which the runtime role deliberately lacks.
    url: process.env["ADMIN_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
